language: cpp
compiler:
        - clang
        - gcc

before_install:
        - sudo apt-get update
        - sudo apt-get install xorg-dev libglu1-mesa-dev x11proto-xf86vidmode-dev

install:
        - wget https://github.com/glfw/glfw/archive/3.0.4.tar.gz
        - tar -xzvf 3.0.4.tar.gz
        - pushd glfw-3.0.4/
        - cmake .
        - make
        - sudo make install
        - popd
        - sudo apt-get install libglm-dev

before_script:
        - pushd build/

script:
        - cmake ..
        - make

after_script:
        - popd

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "n7yIlZrM4O/ECtPgmWlUZr4PiqW8JqkhWF8yJCrV+gzOttXajFVfoNYVyG3mSPd74M8VNcEM8CACMKrGP30tqs71nDMv63CUi5JvE/jIgp931bwJM7FnuWonLTK6GCO1SkWeT01OaakGSLMu0oxXq2oPbwQ0PkfKtkYCJpxwJN0="

addons:
  coverity_scan:
    project:
      name: "leftmostcat/mortar-eng"
    notification_email: leftmostcat@gmail.com
    build_command_prepend: "cd build && make clean"
    build_command: "make"
    branch_pattern: coverity_scan
